Init commit
artromone/spbspu-labs-2023-java-oop1 pull request #1
Opened 2023-09-16 13:14 UTC by artromone

2023-09-18 06:58 UTC, Coding-Seal approved these changes

2023-09-20 20:19 UTC, dimkashelk commented
А где класс Hero?

2023-09-20 20:26 UTC, artromone commented
Там на почте принять надо. Неудобно но как есть. Причем видимо каждый раз

2023-09-20 21:23 UTC, Coding-Seal commented on romanovich.artem/J1/src/main/java/org/example/CommandProcessor.java
> +  }
Герои рождаются, двигаются и умирают )

2023-09-20 21:25 UTC, Coding-Seal commented on romanovich.artem/J1/src/main/java/org/example/Hero.java
> +  }
Предлагаю дать возможность герою подстраиваться под ситуацию и менять стратегию

2023-09-20 21:28 UTC, Coding-Seal commented on romanovich.artem/J1/src/main/java/org/example/Hero.java
> +  }
Предлагаю дать возможность герою подстраиваться под ситуацию и менять стратегию

2023-09-20 21:28 UTC, Coding-Seal commented on romanovich.artem/J1/src/main/java/org/example/CommandProcessor.java
> +    hero.move();
Герои рождаются, двигаются и умирают )

2023-09-20 21:44 UTC, artromone commented on romanovich.artem/J1/src/main/java/org/example/CommandProcessor.java
> +    hero.move();
Тут надо на несколько функций делить по хорошему. По сути sendHero может отвечать за создание юнита и его отправку, используя определенную стратегию. Если есть варианты как лучше разбить, буду рад исправить. Может еще подумаю попопзже.

2023-09-20 21:44 UTC, artromone commented on romanovich.artem/J1/src/main/java/org/example/Hero.java
> +  }
Это мем или ты серьезно?? 😶‍🌫️

2023-09-21 21:17 UTC, LagushkaLaga requested changes

2023-09-21 21:17 UTC, LagushkaLaga commented on romanovich.artem/J1/.idea/vcs.xml
> +<project version="4">
убери .idea из pull request

2023-09-22 19:48 UTC, Coding-Seal approved these changes

2023-09-22 19:49 UTC, merged